# Generated by Django 4.2.7 on 2025-11-20 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "subject_id",
                    models.CharField(
                        max_length=10, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["subject_id"],
            },
        ),
        migrations.CreateModel(
            name="EvaluationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_id", models.CharField(max_length=10)),
                ("session_id", models.CharField(max_length=10)),
                ("session_type", models.CharField(max_length=1)),
                ("filename", models.CharField(max_length=100)),
                ("n_trials", models.IntegerField()),
                ("n_channels", models.IntegerField()),
                ("n_times", models.IntegerField()),
                ("sampling_rate", models.FloatField()),
                ("duration_per_trial", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="api.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["subject", "session_id"],
                "unique_together": {("subject", "run_id")},
            },
        ),
        migrations.CreateModel(
            name="TrialData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trial_index", models.IntegerField()),
                ("ground_truth", models.IntegerField()),
                ("data_json", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trials",
                        to="api.evaluationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["run", "trial_index"],
                "indexes": [
                    models.Index(
                        fields=["run", "trial_index"],
                        name="api_trialda_run_id_07b27b_idx",
                    )
                ],
                "unique_together": {("run", "trial_index")},
            },
        ),
    ]
